### ISSUE TITLE
Inconvenient CRLF in Synonyms

### ISSUE THREAD

**Issue by jump2conclusionsmatt** [USEPA/Federal-LCA-Commons-Elementary-Flow-List#14]
A few of the synonyms entries have CRLFs (/r/n) encoded within the text which makes for some odd CSV exports. See Lasiocarpine for an example.

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt Thanks for noting. Currently the synonyms themselves are not exposed in the API output (see [FlowList](url)), so I suppose this is just an issue when trying to work with an older version, or with the input files more directly?

**Comment by WesIngwersen** [comment]
Manually fixed in chemicalflowables input file https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/commit/0d2ee0767d2a3e8cfbad0f0e6f388fd9cb9628fe 
and added a test for this in future versions of input files https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/commit/2c840d8eb1c20bc73f41501d70616239047de428
